apiVersion: shipa.crossplane.io/v1alpha1
kind: App
metadata:
  name: gitops-app1
spec:
  forProvider:
    name: gitops-app1
    teamowner: shipa-team
    framework: aks-prod

---

apiVersion: shipa.crossplane.io/v1alpha1
kind: AppDeploy
metadata:
  name: gitops-app1-deploy
spec:
  forProvider:
    app: gitops-app1
    image: "ghcr.io/podtato-head/podtatoserver:v0.1.1"
