apiVersion: shipa.crossplane.io/v1alpha1
kind: App
metadata:
  name: gitops-app1
spec:
  forProvider:
    name: gitops-app1
    teamowner: shipa-team
    framework: shipayaml

---

apiVersion: shipa.crossplane.io/v1alpha1
kind: AppDeploy
metadata:
  name: gitops-app1-deploy
spec:
  forProvider:
    app: gitops-app1
    image: "docker.io/shipasoftware/bulletinboard:1.0"
