apiVersion: shipa.crossplane.io/v1alpha1
kind: Framework
metadata:
  name: project1
spec:
  forProvider:
    shipaFramework: project1
    resources:
      general:
        setup:
          provisioner: kubernetes
        router: traefik
        appQuota:
          limit: "4"
        security:
          disableScan: true
          scanPlatformLayers: false
        networkPolicy:
          ingress:
            policy_mode: allow-all
          egress:
            policy_mode: allow-all
          disableAppPolicies: false

---

apiVersion: shipa.crossplane.io/v1alpha1
kind: Framework
metadata:
  name: project2
spec:
  forProvider:
    shipaFramework: project2
    resources:
      general:
        setup:
          provisioner: kubernetes
        router: traefik
        appQuota:
          limit: "8"
        security:
          disableScan: true
          scanPlatformLayers: false
        networkPolicy:
          ingress:
            policy_mode: allow-all
          egress:
            policy_mode: allow-all
          disableAppPolicies: false

---

apiVersion: shipa.crossplane.io/v1alpha1
kind: Framework
metadata:
  name: project3
spec:
  forProvider:
    shipaFramework: project3
    resources:
      general:
        setup:
          provisioner: kubernetes
        router: traefik
        appQuota:
          limit: "10"
        security:
          disableScan: true
          scanPlatformLayers: false
        networkPolicy:
          ingress:
            policy_mode: allow-all
          egress:
            policy_mode: allow-all
          disableAppPolicies: false

